name: Add LinkedIn Insight Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Insight Tag to HTML
        shell: bash
        run: |
          set -euo pipefail
          snippet_file=".github/li_snippet.html"
          cat > "$snippet_file" <<'SNIP'
          <script type="text/javascript">
          _linkedin_partner_id = "7754636";
          window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
          window._linkedin_data_partner_ids.push(_linkedin_partner_id);
          </script>
          <script type="text/javascript">
          (function(l) {
          if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
          window.lintrk.q=[]}
          var s = document.getElementsByTagName("script")[0];
          var b = document.createElement("script");
          b.type = "text/javascript";b.async = true;
          b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
          s.parentNode.insertBefore(b, s);})(window.lintrk);
          </script>
          <noscript>
          <img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=7754636&fmt=gif" />
          </noscript>
          SNIP

          changed=0
          while IFS= read -r -d '' f; do
            # Already has LI script?
            if grep -q 'snap\.licdn\.com/li\.lms-analytics/insight\.min\.js' "$f"; then
              continue
            fi
            if grep -qi '</head>' "$f"; then
              # Insert before </head>
              awk -v RS= -v ORS= -v snip="$(cat "$snippet_file")" \
                '{sub(/<\/head>/, snip "\n</head>"); print}' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
            else
              # No </head>: append to end
              printf '\n%s\n' "$(cat "$snippet_file")" >> "$f"
            fi
            echo "Patched: $f"
            changed=1
          done < <(find . -type f -name "*.html" -print0)

          if [ $changed -eq 0 ]; then
            echo "No files needed changes."
          fi

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "titan-bot"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "chore(marketing): inject LinkedIn Insight Tag across HTML"
            git push
          else
            echo "Nothing to commit."
          fi
