name: Add LinkedIn Insight Tag

on:
  push:
    branches: [ main ]
    # re-run when HTML changes or when this workflow changes
    paths:
      - '**/*.html'
      - '.github/workflows/add_linkedin_tag.yml'

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inject LI Insight Tag into HTML (id: 7754636)
        run: |
          python3 - <<'PY'
          import re, glob, os
          SNIPPET = """<script type="text/javascript">
          _linkedin_partner_id = "7754636";
          window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
          window._linkedin_data_partner_ids.push(_linkedin_partner_id);
          </script><script type="text/javascript">
          (function(l) {
          if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
          window.lintrk.q=[]}
          var s = document.getElementsByTagName("script")[0];
          var b = document.createElement("script");
          b.type = "text/javascript";b.async = true;
          b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
          s.parentNode.insertBefore(b, s);})(window.lintrk);
          </script>
          <noscript>
          <img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=7754636&fmt=gif" />
          </noscript>
          """
          needle = re.compile(r'snap\.licdn\.com/li\.lms-analytics/insight\.min\.js')
          changed = False
          for path in glob.glob("**/*.html", recursive=True):
              with open(path, "r", encoding="utf-8", errors="ignore") as f:
                  html = f.read()
              if needle.search(html):
                  continue
              m = re.search(r'</head\s*>', html, re.I)
              if m:
                  html = html[:m.start()] + SNIPPET + "\n" + html[m.start():]
              else:
                  html += "\n" + SNIPPET + "\n"
              with open(path, "w", encoding="utf-8") as f:
                  f.write(html)
              print(f"Inserted LI tag into {path}")
              changed = True
          if not changed:
              print("No files needed changes.")
          PY

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "titan-bot"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "chore(marketing): inject LinkedIn Insight Tag across HTML"
            git push
          else
            echo "Nothing to commit."
          fi
