name: Publish Founding Beta

on:
  push:
    paths:
      - ".github/workflows/founding_beta_publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOMAIN: titancraft.io
      GTAG_ID: AW-17498661419
      PRICE_USD: "29"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Stripe SDK
        run: pip install stripe==7.11.0

      - name: Create Stripe product, price, and payment link
        id: stripe
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: |
          python - <<'PY'
          import os, stripe
          key = os.environ.get('STRIPE_SECRET_KEY')
          if not key:
              # No secret means skip without failing the job
              print('NO_STRIPE_KEY=1')
              raise SystemExit(0)
          stripe.api_key = key
          name = 'Founding Beta Access'
          price_amount = int(float(os.environ.get('PRICE_USD','29'))*100)
          # find or create product
          prods = stripe.Product.list(active=True, limit=100)
          prod = next((p for p in prods.data if p.name==name), None)
          if not prod:
              prod = stripe.Product.create(name=name, metadata={'tag':'titan_founding_beta_v1'})
          # find or create monthly price
          prices = stripe.Price.list(product=prod.id, active=True, limit=100)
          price = next((x for x in prices.data if x.recurring and x.unit_amount==price_amount and x.currency=='usd'), None)
          if not price:
              price = stripe.Price.create(product=prod.id, unit_amount=price_amount, currency='usd', recurring={'interval':'month'})
          # create payment link with redirect to success page
          domain = os.environ.get('DOMAIN','titancraft.io')
          success_url = f"https://{domain}/founding-beta/success.html"
          plink = stripe.PaymentLink.create(
              line_items=[{"price": price.id, "quantity": 1}],
              after_completion={"type": "redirect", "redirect": {"url": success_url}},
              allow_promotion_codes=False
          )
          with open('plink.txt','w') as f:
              f.write(plink.url)
          print('PAYMENT_LINK=' + plink.url)
          PY

      - name: Prepare site files
        run: |
          mkdir -p founding-beta
          # read link if present, else leave placeholder
          LINK="REPLACE_WITH_STRIPE_CHECKOUT_URL"
          if [ -f plink.txt ]; then LINK=$(cat plink.txt); fi

          cat > founding-beta/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>TitanCraft — Founding Beta Access</title>
              <script async src="https://www.googletagmanager.com/gtag/js?id=GTAG_PLACEHOLDER"></script>
              <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);} 
                gtag('js', new Date());
                gtag('config', 'GTAG_PLACEHOLDER');
              </script>
              <style>
                :root { --bg:#0b0b10; --card:#12121a; --text:#e8e8f0; --muted:#a8a8bf; --accent:#5aa9ff; }
                html,body { margin:0; padding:0; background:var(--bg); color:var(--text); font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,Arial,sans-serif; }
                .wrap { max-width:980px; margin:0 auto; padding:40px 20px; }
                header { display:flex; justify-content:space-between; align-items:center; gap:16px; }
                .logo { font-weight:700; letter-spacing:0.5px; }
                .card { background:var(--card); border-radius:16px; padding:28px; box-shadow:0 10px 30px rgba(0,0,0,0.25); }
                h1 { font-size: 2.2rem; margin: 0 0 12px; }
                p.lead { font-size:1.15rem; color:var(--muted); margin:0 0 20px; }
                .cta { display:flex; gap:12px; margin-top:18px; flex-wrap:wrap; }
                .btn { background:var(--accent); color:#071018; padding:14px 20px; border-radius:12px; text-decoration:none; font-weight:700; }
                .btn.secondary { background:transparent; border:1px solid #2a2a3a; color:var(--text); }
                .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:14px; margin-top:18px; }
                .pill { background:#191924; border:1px solid #27273a; padding:14px; border-radius:12px; color:var(--muted); }
                footer { margin-top:32px; font-size:0.95rem; color:var(--muted); display:flex; gap:18px; flex-wrap:wrap; }
                a { color:var(--accent); }
              </style>
            </head>
            <body>
              <div class="wrap">
                <header>
                  <div class="logo">TitanCraft</div>
                  <nav><a href="#how">How it works</a></nav>
                </header>

                <main class="card">
                  <h1>Beat ChatGPT by routing to the best specialist models</h1>
                  <p class="lead">TitanCraft routes each prompt to the model that wins for that task, you get stronger answers with less effort.</p>
                  <div class="cta">
                    <a class="btn" href="REPLACE_WITH_STRIPE_CHECKOUT_URL">Get Founding Beta Access, $PRICE_PLACEHOLDER/mo</a>
                    <a class="btn secondary" href="#how">How it works</a>
                  </div>
                  <div class="grid">
                    <div class="pill">Automatic model routing, tuned to your prompt type</div>
                    <div class="pill">Benchmark driven selection, not guesswork</div>
                    <div class="pill">Concierge onboarding for early users, setup done for you</div>
                    <div class="pill">Seven day no questions refund</div>
                  </div>
                </main>

                <section id="how" class="card" style="margin-top:14px;">
                  <h2>How it works</h2>
                  <ol>
                    <li>Pay for Founding Beta Access, secure checkout by Stripe</li>
                    <li>Complete a sixty second intake</li>
                    <li>We configure routing for your top use cases, you receive first results in seventy two hours</li>
                  </ol>
                </section>

                <section class="card" style="margin-top:14px;">
                  <h2>FAQ</h2>
                  <p><strong>Do I need a dashboard to start</strong><br>No, early users get concierge onboarding and results by email, the UI unlocks as we scale.</p>
                  <p><strong>What if it is not a fit</strong><br>Ask within seven days, we refund in full.</p>
                  <p><strong>What models do you use</strong><br>We route among leading providers and specialist GPTs, the mix changes as benchmarks improve.</p>
                </section>

                <footer>
                  <a href="/privacy.html">Privacy</a>
                  <a href="/terms.html">Terms</a>
                  <a href="/founding-beta/success.html">After checkout</a>
                </footer>
              </div>
            </body>
          </html>
          HTML

          sed -i "s|REPLACE_WITH_STRIPE_CHECKOUT_URL|$LINK|g" founding-beta/index.html
          sed -i "s|GTAG_PLACEHOLDER|$GTAG_ID|g" founding-beta/index.html
          sed -i "s|PRICE_PLACEHOLDER|$PRICE_USD|g" founding-beta/index.html

          cat > founding-beta/success.html <<'HTML'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Thank you, Founding Beta confirmed</title>
              <script async src="https://www.googletagmanager.com/gtag/js?id=GTAG_PLACEHOLDER"></script>
              <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);} 
                gtag('js', new Date());
                gtag('config', 'GTAG_PLACEHOLDER');
                window.addEventListener('load', function(){ gtag('event','purchase',{value:PRICE_PLACEHOLDER, currency:'USD'}); });
              </script>
              <style>
                body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Arial, sans-serif; padding: 40px; background:#0b0b10; color:#e8e8f0; }
                a { color:#5aa9ff; }
                .card { max-width:760px; margin:0 auto; background:#12121a; padding:28px; border-radius:16px; }
              </style>
            </head>
            <body>
              <div class="card">
                <h1>You are in, Founding Beta confirmed</h1>
                <p>Thank you for joining. Your onboarding email arrives within minutes. If you do not see it, check spam.</p>
                <p>Timeline, within seventy two hours you will receive your first routed results and access details.</p>
                <p>Need help, email <a href="mailto:TitanCraftAI@gmail.com">TitanCraftAI@gmail.com</a>. Refund policy, seven days, no questions.</p>
                <p><a href="/founding-beta/">Return to home</a></p>
              </div>
            </body>
          </html>
          HTML
          sed -i "s|GTAG_PLACEHOLDER|$GTAG_ID|g" founding-beta/success.html
          sed -i "s|PRICE_PLACEHOLDER|$PRICE_USD|g" founding-beta/success.html

          echo "/ /founding-beta/ 302" > _redirects

      - name: Commit and push
        run: |
          git config user.name "titan-bot"
          git config user.email "bot@titancraft.io"
          git add founding-beta _redirects || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add Founding Beta landing and success page, route root to founding beta"
            git push origin HEAD:main
          fi
