name: Marketing — Structured Meta (JSON-LD + OG/Twitter)

on:
  workflow_dispatch:
  schedule:
    - cron: '17 9 * * 1,3,5' # Mon/Wed/Fri 09:17 UTC

permissions:
  contents: write

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate JSON-LD + social meta
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
          import json, pathlib
          site = "https://titancraft.io"
          org = {
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "TitanCraft AI",
              "url": site,
              "logo": f"{site}/public/logo.png",
              "sameAs": [
                  "https://x.com/titancraftai",
                  "https://www.linkedin.com/company/titancraft-ai"
              ]
          }
          p = pathlib.Path("public")
          p.mkdir(parents=True, exist_ok=True)
          (p/"site.schema.json").write_text(json.dumps(org, indent=2))

          meta = f"""<meta property="og:title" content="TitanCraft AI">
          <meta property="og:description" content="Beat ChatGPT by routing to the best specialist models.">
          <meta property="og:url" content="{site}">
          <meta property="og:type" content="website">
          <meta property="og:image" content="{site}/public/logo.png">
          <meta name="twitter:card" content="summary_large_image">
          <meta name="twitter:site" content="@titancraftai">
          """
          (p/"structured_meta.html").write_text(meta)
          PY

      - name: Commit & push meta (safe)
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "titan-bot"
          git config user.email "titan-bot@users.noreply.github.com"
          git add public/site.schema.json public/structured_meta.html || true
          if git diff --cached --quiet; then
            echo "No meta changes; skipping push."; exit 0
          fi
          branch="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
          git pull --rebase origin "$branch" || true
          git commit -m "chore(marketing): update JSON-LD + social meta"
          git push origin "HEAD:$branch"

      - name: Ping Google & Bing
        shell: bash
        run: |
          curl -fsS "https://www.google.com/ping?sitemap=https://titancraft.io/sitemap.xml" || true
          curl -fsS "https://www.bing.com/ping?sitemap=https://titancraft.io/sitemap.xml" || true
