name: Marketing — Structured Data (JSON-LD + OG/Twitter)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '15 8 * * *'  # daily @ 08:15 UTC

permissions:
  contents: write

jobs:
  structured_meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate JSON-LD + OG/Twitter tags
        run: |
          python - <<'PY'
          import json, pathlib
          site = "https://titancraft.io"
          org = {
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": "TitanCraft AI",
            "url": site,
            "logo": site + "/public/logo.png",
            "sameAs": [
              "https://x.com/titancraftai",
              "https://www.linkedin.com/company/titancraft-ai"
            ]
          }
          p = pathlib.Path("public")
          p.mkdir(exist_ok=True)
          (p/"site.schema.json").write_text(json.dumps(org, indent=2))
          tags = f"""<meta property="og:title" content="TitanCraft AI">
<meta property="og:description" content="Beat ChatGPT by routing to the best specialist models.">
<meta property="og:url" content="{site}">
<meta property="og:type" content="website">
<meta property="og:image" content="{site}/public/og.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@titancraftai">
"""
          (p/"structured_meta.html").write_text(tags)
          PY

      - name: Commit & push meta (safe)
        run: |
          set -euxo pipefail
          git config user.name "titan-bot"
          git config user.email "titan-bot@users.noreply.github.com"
          git add public/site.schema.json public/structured_meta.html || true
          if git diff --cached --quiet; then
            echo "No meta changes; skipping push."
            exit 0
          fi
          branch="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
          git pull --rebase origin "$branch" || true
          git commit -m "chore(marketing): update JSON-LD + OG/Twitter meta"
          git push origin "HEAD:$branch"
